
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described 
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: api
    context: src/api
  - image: nameservice
    context: src/nameservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
