apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: server
          image: api
          ports:
          - containerPort: 8080
          env:
          - name: NAME_SERVICE_ADDR
            value: "nameservice:9556"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: grpc
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-external
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
  - name: grpc
    port: 5000
    targetPort: 5000
    nodePort: 32000
